//! The `--echo-console` line: one captured frame in candump-ish format.
//!
//! ```text
//! B0 (1.234_567) 123 S [8] 00 41 7E 1F 20 7F FF 42 | .A~. ..B
//! ```
//!
//! An operator's diagnostic rather than a protocol — nothing on a wire ever
//! sees this — so it sits beside the pipeline rather than under `gvret`.
//!
//! Pure and synchronous — the caller owns the buffer and the write — so the
//! bytes can be asserted against lines generated by running the Python's
//! `format_candump_line` itself, which is where every expectation in the tests
//! below came from.

use std::fmt::Write;

use wiretap_model::{payload_dlc, CanSample};

const RED: &str = "\x1b[31m";
const YELLOW: &str = "\x1b[33m";
const RESET: &str = "\x1b[0m";

/// The hex column's width for a classic frame: eight bytes of `XX ` less the
/// trailing space, so the `|` lines up whatever the payload length.
const CLASSIC_HEX_WIDTH: usize = 23;

fn printable(b: u8) -> bool {
    (0x20..=0x7E).contains(&b)
}

/// Append one frame's line, including its newline.
///
/// `rel_us` is microseconds since the server started, which is what the Python
/// printed: it read the clock as it formatted rather than using the frame's
/// capture timestamp, and the absolute-time branch beside it was unreachable
/// from the capture loop.
pub fn format_line(out: &mut String, s: &CanSample, colour: bool, rel_us: u64) {
    if colour {
        out.push_str(YELLOW);
    }
    let _ = write!(out, "B{} ", s.bus.0);
    if colour {
        out.push_str(RESET);
    }

    let (sec, rem) = (rel_us / 1_000_000, rel_us % 1_000_000);
    let _ = write!(out, "({}.{:03}_{:03}) ", sec, rem / 1_000, rem % 1_000);

    if s.extended {
        let _ = write!(out, "{:08X} E", s.arb_id);
    } else {
        let _ = write!(out, "{:03X} S", s.arb_id);
    }
    if s.is_fd {
        out.push('F');
    }
    // No R, ! , B or E flag can ever follow. Remote frames are dropped by the
    // reader and error frames are never delivered (docs/porting-notes.md); the
    // bit rate switch and error state indicator are the real loss, and a
    // `CanSample` does not carry them because nothing else in the pipeline —
    // the archive included — has anywhere to put them.

    let _ = write!(out, " [{}] ", payload_dlc(s.data.len(), s.is_fd));

    // Padding is measured over what was written, escape sequences included,
    // exactly as the Python's `ljust` over an already-coloured string: with
    // colour on, a frame carrying printable bytes is wide enough already and
    // the column does not line up. Replicated rather than fixed, so a diff
    // against the Python is empty.
    let hex_from = out.len();
    for (i, &b) in s.data.iter().enumerate() {
        if i > 0 {
            out.push(' ');
        }
        let lit = colour && printable(b);
        if lit {
            out.push_str(RED);
        }
        let _ = write!(out, "{b:02X}");
        if lit {
            out.push_str(RESET);
        }
    }
    // An FD frame pads to `data_len * 3 - 1`, which is exactly the width it
    // just wrote, so only classic frames ever gain a space — in the Python's
    // `ljust` as much as here.
    if !s.is_fd {
        for _ in (out.len() - hex_from)..CLASSIC_HEX_WIDTH {
            out.push(' ');
        }
    }

    out.push_str(" | ");
    for &b in &s.data {
        let shown = printable(b);
        if colour && shown {
            out.push_str(RED);
        }
        out.push(if shown { char::from(b) } else { '.' });
        if colour && shown {
            out.push_str(RESET);
        }
    }
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;
    use wiretap_model::{Direction, SourceId};

    /// 1.234_567 s of uptime, the value the golden lines were generated at.
    const REL_US: u64 = 1_234_567;

    fn sample(bus: u8, arb_id: u32, extended: bool, is_fd: bool, data: &[u8]) -> CanSample {
        CanSample {
            ts_us: 0,
            arb_id,
            extended,
            is_fd,
            data: data.to_vec(),
            bus: SourceId(bus),
            dir: Direction::Rx,
        }
    }

    fn line(s: &CanSample, colour: bool) -> String {
        let mut out = String::new();
        format_line(&mut out, s, colour, REL_US);
        out
    }

    // --- golden lines, generated by running the Python's format_candump_line
    //     over the equivalent raw frames ------------------------------------

    #[test]
    fn a_standard_frame_matches_the_python() {
        let s = sample(
            0,
            0x123,
            false,
            false,
            &[0x00, 0x41, 0x7E, 0x1F, 0x20, 0x7F, 0xFF, 0x42],
        );
        assert_eq!(
            line(&s, false),
            "B0 (1.234_567) 123 S [8] 00 41 7E 1F 20 7F FF 42 | .A~. ..B\n"
        );
    }

    /// The column is padded to a fixed width so the `|` lines up.
    #[test]
    fn a_short_payload_pads_the_hex_column() {
        let s = sample(0, 0x7FF, false, false, &[0x41, 0x42, 0x43]);
        assert_eq!(
            line(&s, false),
            "B0 (1.234_567) 7FF S [3] 41 42 43                | ABC\n"
        );

        let s = sample(7, 0x100, false, false, &[]);
        assert_eq!(
            line(&s, false),
            "B7 (1.234_567) 100 S [0]                         | \n"
        );
    }

    #[test]
    fn an_extended_id_is_eight_digits_and_tagged_e() {
        let s = sample(1, 0x18DA_F110, true, false, &[0xDE, 0xAD]);
        assert_eq!(
            line(&s, false),
            "B1 (1.234_567) 18DAF110 E [2] DE AD                   | ..\n"
        );
    }

    /// FD sets the `F` tag, prints the data length *code*, and needs no
    /// padding — the column is exactly as wide as the payload.
    #[test]
    fn an_fd_frame_prints_the_code_and_is_not_padded() {
        let s = sample(2, 0x200, false, true, &(0x40..0x4C).collect::<Vec<u8>>());
        assert_eq!(
            line(&s, false),
            "B2 (1.234_567) 200 SF [9] 40 41 42 43 44 45 46 47 48 49 4A 4B | @ABCDEFGHIJK\n"
        );
    }

    /// Colour wraps each printable byte individually, in both columns, and the
    /// bus tag is yellow — including its trailing space.
    #[test]
    fn colour_marks_printable_bytes_in_both_columns() {
        let s = sample(0, 0x7FF, false, false, &[0x41, 0x42, 0x43]);
        assert_eq!(
            line(&s, true),
            "\x1b[33mB0 \x1b[0m(1.234_567) 7FF S [3] \
             \x1b[31m41\x1b[0m \x1b[31m42\x1b[0m \x1b[31m43\x1b[0m | \
             \x1b[31mA\x1b[0m\x1b[31mB\x1b[0m\x1b[31mC\x1b[0m\n"
        );
    }

    /// The quirk that falls out of padding a string that already holds escape
    /// sequences: the pad counts them, so how far the `|` moves depends on how
    /// many bytes were printable.
    #[test]
    fn colour_is_padded_over_its_own_escape_sequences() {
        let s = sample(1, 0x18DA_F110, true, false, &[0xDE, 0xAD]);
        assert_eq!(
            line(&s, true),
            "\x1b[33mB1 \x1b[0m(1.234_567) 18DAF110 E [2] DE AD                   | ..\n",
            "nothing printable, so the column lines up as usual"
        );

        let s = sample(0, 0x100, false, false, &[0x41]);
        assert_eq!(
            line(&s, true),
            "\x1b[33mB0 \x1b[0m(1.234_567) 100 S [1] \x1b[31m41\x1b[0m             | \x1b[31mA\x1b[0m\n",
            "eleven escaped characters, padded to twenty-three"
        );

        // Three of them overrun it, which is why the coloured column in
        // `colour_marks_printable_bytes_in_both_columns` is not padded at all.
        let s = sample(0, 0x100, false, false, &[0x41, 0x42, 0x43]);
        assert!(line(&s, true).contains("\x1b[31m43\x1b[0m | "));
    }

    #[test]
    fn the_uptime_is_seconds_then_milliseconds_then_microseconds() {
        let s = sample(0, 1, false, false, &[]);
        let stamp = |us| {
            let mut out = String::new();
            format_line(&mut out, &s, false, us);
            out.split(") ").next().unwrap().to_string()
        };
        assert_eq!(stamp(0), "B0 (0.000_000");
        assert_eq!(stamp(7), "B0 (0.000_007");
        assert_eq!(stamp(1_020_003), "B0 (1.020_003");
        assert_eq!(stamp(3_600_000_000), "B0 (3600.000_000");
    }
}
